// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlx853y0TjKCM5zgYWfxAoZLzVn89L2lI',
    appId: '1:177980538361:web:afb31560ae2a920be71128',
    messagingSenderId: '177980538361',
    projectId: 'zenithrabitai',
    authDomain: 'zenithrabitai.firebaseapp.com',
    storageBucket: 'zenithrabitai.appspot.com',
    measurementId: 'G-EG45GNSH5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0OMVogiHfg_MkuLhDqoWbPBQUWlelGOk',
    appId: '1:177980538361:android:77715288b403453ee71128',
    messagingSenderId: '177980538361',
    projectId: 'zenithrabitai',
    storageBucket: 'zenithrabitai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDH5_RZsK5Hg5b6SlraIMvYoIhtJtJOP8',
    appId: '1:177980538361:ios:129276d31dd8c5ede71128',
    messagingSenderId: '177980538361',
    projectId: 'zenithrabitai',
    storageBucket: 'zenithrabitai.appspot.com',
    androidClientId: '177980538361-s9ht1e8jnchiatrr1vk7rorloqdl295d.apps.googleusercontent.com',
    iosClientId: '177980538361-p04pq0nb86mp69rp84oh4dmefri6ef1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenithrabitai',
  );

}